### ISSUE TITLE
Add to README: instructions for compiling with newer zlib

### ISSUE THREAD

**Issue by giovtorres** [vcftools/vcftools#29]
RHEL 6 has zlib v1.2.3.  With this version of zlib, vcftools outputs at runtime:

```
Using zlib version: 1.2.3
Versions of zlib >= 1.2.4 will be *much* faster when reading zipped VCF files.
```

It is not clear from the README or the documentation page how to build vcftools with a newer zlib.  I found the following to work:

```
export ZLIB_LIBS=-L/path/to/zlib/lib -lz
export ZLIB_CFLAGS=-I/path/to/zlib/include
./configure
make
make install
```

Might save some users some time when trying to compile.

Thanks.

**Comment by wookietreiber** [comment]
There are actually multiple ways to achieve this. Setting `ZLIB_LIBS` and `ZLIB_CFLAGS` is one of them.

The more common way is to point `pkg-config` to your zlib installation:

    export PKG_CONFIG_PATH="/path/to/zlib/lib/pkgconfig:$PKG_CONFIG_PATH"

Another way is to set `CPPFLAGS` and `LDFLAGS` directly, but this is generally less recommended if there is `pkg-config` support.

---

I don't see a necessity to put these instructions into README because all of these three ways are both really common practice and documented in `./configure --help`.

**Comment by giovtorres** [comment]
OK thanks.

**Comment by map2085** [comment]
I found this really helpful.  The "pkg-config" solution being the easiest.

But this isn't necessarily common knowledge for everyone.  Bioinformatics users certainly have a wide range of familiarity with these sorts of things.  It would be very helpful to be in the README.

**Comment by wookietreiber** [comment]
@map2085 Well, your distribution / package manager *should* actually be responsible for setting up your local `PKG_CONFIG_PATH`, e.g. via `/etc/profile.d/`. If that's not done properly, especially for non-standard paths, you may also address this to your distribution / package manager support.
